# -*- coding:Utf-8 -*-

'''
HistoryItem constants
'''

HISTORY_GENERATED_STATE = 1
HISTORY_PAID_STATE = 2
HISTORY_ACCEPTED_STATE = 3
HISTORY_DENIED_STATE = 4

HISTORY_USERREQUEST_TYPE = 1
HISTORY_CREDITREQUEST_TYPE = 2
HISTORY_PAIDREQUEST_TYPE = 3

'''
AdminLog constants
'''

ADMINLOG_USERREQUEST_ACCEPTED = 1
ADMINLOG_CREDITREQUEST_ACCEPTED = 2
ADMINLOG_PAIDREQUEST_ACCEPTED = 3

ADMINLOG_USERREQUEST_INVALID_PAYMENT = 4
ADMINLOG_CREDITREQUEST_INVALID_PAYMENT = 5

ADMINLOG_USERREQUEST_PAID = 6

ADMINLOG_USERREQUEST_DENIED = 14
ADMINLOG_CREDITREQUEST_DENIED = 15
ADMINLOG_PAIDREQUEST_DENIED = 16
